Adding credential provider
Attempt to fix 
org.eclipse.jgit.api.errors.TransportException: https://github.com/vsair/rocketmq.git: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:250)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:304)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:201)
	at com.chbrown13.pull_rec.Utils.checkout(Utils.java:486)
	at com.chbrown13.pull_rec.PullRecommender.analyze(PullRecommender.java:64)
	at com.chbrown13.pull_rec.PullRecommender.main(PullRecommender.java:125)
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/vsair/rocketmq.git: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:524)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:341)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1236)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:239)
	... 5 more